version: '3.0'
services:
    nodeserver:
      build: ./emailsGenerator/
      container_name: apiEmails
      ports:
        - "3000:3000"
      volumes: 
        - "./emailsGenerator/:/app"
        - "/app/node_modules"
      command: npm start
    nginx:
        restart: always
        build: ./nginx/
        ports:
          - "80:80"